### PR TITLE
Feature/change way to set label on button

### LINKED ISSUE #12: Displaying the selected item in the button
Can I display the selected item in the button? In the parameters, you can specify label, but it would be more convenient to display the selected element

### PR DESCRIPTION
**Pull request by IneoO**
resolve #12

### CODE REVIEW

**Comment by amc1999** [comment]
Question:  Why we now using `labelValue` as `buttonLabel` now?
I understand, it was likely some reason, but I cannot track it down in history of changes of `getBtnLabel()`.

Original commit was `labelName`: 
```
  return this.valueSelected[this.valueSelected.length - 1][this.labelName];
```
and now line 318 of vue-multi-select.js  is using `labelValue`:
```
  return this.valueSelected[this.valueSelected.length - 1][this.labelValue];
```

As result single select label look bit odd (in my opinion), for example for:
```
selectOptions: [
  { val: 'F', name: 'Female' },
  { val: 'M', name: 'Male' },
  { val: 'T', name: 'Total' }
],
options: {
  multi: false,
  labelName: 'name',
  labelValue: 'val'
}
```
In drop-down we see `Female, Male, Total` and after click button label is one of: `F, M, T` and it does look strange.

Do you want PR for such changes? or CodePen example with options above?

Feature to discuss:
In general it would be nice to have `options.btnLabel` as string or function, that would us to replace `getBtnLabel()` with some custom rendering, similar to `cssSelected` and `renderTemplate`

Thank you for vue-multi-select :)

**Comment by IneoO** [comment]
Hi, yeah, it's a mistake. The render function for buttonLabel is the best way. I will make a pr before the end of the week-end 

Thx

**Comment by IneoO** [comment]
it's done thx.

**Comment by amc1999** [comment]
Thank you

**Comment by amc1999** [comment]
Documentation suggestion:
It may be a good idea to have an example of `btnLabel` in example2 of doc.js / doc.vue
It can be something like:
```
<multi-select
     :btnLabel="(selection) => (selection.length > 0 ? selection[0].name : 'Select...')"
............
```
or
```
<multi-select
      :btnLabel="btnLabel"
............
  data () {
    return {
      btnLabel: (selection) => (selection.length > 0 ? selection[0].name : 'Select...'),
............
```

**Comment by IneoO** [comment]
Yep, i'm gonna do that today or tomorrow

**Pull request merged**
